version: '3.8'

services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app
    depends_on:
      - api
    networks:
      - frontnet

  api:
    build: ./api
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db
    networks:
      - frontnet
      - backnet

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - frontnet

  redis:
    image: redis:alpine
    expose:
      - "6379"
    networks:
      - backnet

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backnet

volumes:
  postgres_data:

networks:
  frontnet:
    driver: bridge
  backnet:
    driver: bridge
