version: '3.8'

services:
  app:
    build: ../../app
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - frontnet

  api:
    build: ../../api
    env_file:
      - ../../.env
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - frontnet
      - backnet

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - frontnet

  redis:
    image: redis:alpine
    expose:
      - "6379"
    networks:
      - backnet

networks:
  frontnet:
    driver: bridge
  backnet:
    driver: bridge
