version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: your_db_name
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ../../../api
    env_file:
      - ../../../.env
    ports:
      - "8080:8080"
    depends_on:
      - db
