name: Deploy on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh/
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan 13.236.165.201 >> ~/.ssh/known_hosts

    - name: SSH and Deploy
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@54.79.40.75 << 'EOF'
          cd res-lasian
          git pull origin main
          cd infra/production
          docker-compose down
          docker-compose build
          docker-compose up -d
          docker-compose restart pdfgenerator
        EOF
